Possible issues:
1. requests.exceptions.SSLError: HTTPSConnectionPool(host='minciencias.gov.co', port=443): Max retries exceeded with url: /convocatorias/todas (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)'))
2. OSError: [Errno 101] Network is unreachable